name: lint

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
    flake8-py3:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install requirements
        run: pip install -r requirements.txt
        
      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 fanreceive/