name: test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
    django-test:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3 

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install requirements
        run: pip install -r requirements.txt
      
      - name: Django migrations
        run: | 
             mkdir fanreceive/db && \
             python fanreceive/manage.py makemigrations && \
             python fanreceive/manage.py migrate --database test --run-syncdb

      - name: Install coverage
        run: pip install coverage

      - name: Django Coverage accounts tests
        run: coverage run --data-file=coverage.xml fanreceive/manage.py test api 

      - name: Django Coverage app tests
        run: coverage run --data-file=coverage.xml fanreceive/manage.py test bid
      
      - name: Django Coverage chat tests
        run: coverage run --data-file=coverage.xml fanreceive/manage.py test matches
      
      - name: Django Coverage order tests
        run: coverage run --data-file=coverage.xml fanreceive/manage.py test users

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage
          path: coverage.xml
          retention-days: 1
